# Generated by Django 4.2.5 on 2023-11-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_userprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.department')),
                ('students', models.ManyToManyField(blank=True, null=True, related_name='courses_registered', to='admin_app.userprofile')),
                ('teachers', models.ManyToManyField(blank=True, null=True, related_name='courses_taught', to='admin_app.userprofile')),
            ],
        ),
    ]
