# Generated by Django 4.2.5 on 2023-11-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_school_alter_department_department_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.program'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.stream'),
        ),
    ]
