# Generated by Django 4.2.5 on 2023-11-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_course_academic_year_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, choices=[('head', 'Head'), ('school dean', 'School Dean'), ('chair', 'Chair'), ('program coordinater', 'Program Coordinator'), ('college dean', 'College Dean')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_registered', to='admin_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='courses_taught', to='admin_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('teacher', 'teacher'), ('staff', 'staff'), ('student', 'student')], default='student', max_length=20),
        ),
    ]
