# Generated by Django 4.2.7 on 2023-12-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_userprofile_position_alter_course_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, choices=[('head', 'Head'), ('school dean', 'School Dean'), ('chair', 'Chair'), ('program coordinator', 'Program Coordinator'), ('college dean', 'College Dean')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('teacher', 'teacher'), ('staff', 'staff'), ('student', 'student')], max_length=20),
        ),
    ]
