# Generated by Django 4.2.5 on 2023-11-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InitialUserProfile',
        ),
    ]
