# Generated by Django 4.2.5 on 2023-11-23 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.profile')),
                ('academic_year', models.CharField(choices=[('1st', 'First'), ('2nd', 'Second'), ('3rd', 'Third'), ('4th', 'Fourth'), ('5th', 'Fifth')], max_length=20)),
                ('semester', models.CharField(choices=[('1st', 'First'), ('2nd', 'Second'), ('summer', 'Summer')], max_length=20)),
            ],
            bases=('website.profile',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(to='admin_app.student')),
                ('teacher', models.ManyToManyField(to='admin_app.teacher')),
            ],
        ),
    ]
